Repository forcedotcom/salesforcedx-vscode, pull requests merged in 2022-06, with the labels that each got.

#4193 chore : add template for getRecords
  packages/salesforcedx-vscode-lwc/snippets/lwc.json
Labels: cla:signed, type:community-contrib

#4147 [Snyk] Security upgrade octicons from 9.1.1 to 9.1.1
  docs/Gemfile.lock
Labels: cla:signed

#4230 chore: Merge user contribution for fixing typo in interactive debugger doc
  docs/_articles/en/apex/interactive-debugger.md
Labels: cla:signed

#4007 Sonal/codebuilder beta
  docs/_articles/en/bugs-and-feedback.md
  docs/_articles/en/codebuilder/about.md
  docs/_articles/en/codebuilder/cb-diffs.md
  docs/_articles/en/codebuilder/cb-setup.md
  docs/_articles/en/codebuilder/cb-start.md
  docs/_articles/en/index.md
  docs/_articles/en/soql/soql-builder.md
  docs/_articles/en/vscode-desktop/desktop-intro.md
  docs/_articles/en/vscode-desktop/install.md
  docs/_articles/en/vscode-desktop/java-setup.md
  docs/_articles/en/vscode-desktop/recommended-extensions.md
  docs/_articles/en/vscode-desktop/settings.md
  docs/_articles/en/vscode-desktop/tips-and-tricks.md
  docs/_articles/ja/codebuilder/about.md
  docs/_articles/ja/codebuilder/cb-diffs.md
  docs/_articles/ja/codebuilder/cb-setup.md
  docs/_articles/ja/codebuilder/cb-start.md
  docs/_articles/ja/vscode-desktop/desktop-intro.md
  docs/_articles/ja/vscode-desktop/install.md
  docs/_articles/ja/vscode-desktop/java-setup.md
  docs/_articles/ja/vscode-desktop/recommended-extensions.md
  docs/_articles/ja/vscode-desktop/settings.md
  docs/_articles/ja/vscode-desktop/tips-and-tricks.md
  docs/_config.yml
  docs/_data/sidebar.yml
  docs/images/cb-intro.gif
  docs/images/code_builder_ui.jpg
  docs/images/codebuilder_welcome.png
  docs/images/grant_access.png
  docs/images/index_intro_small.gif
  docs/images/install_button.png
  docs/images/org_browser_small.jpg
  packages/salesforcedx-vscode/CHANGELOG.md
Labels: Code Builder
