Repository forcedotcom/salesforcedx-vscode, pull requests merged in 2023-04, with the labels that each got.

#4754 fix: SOQL Builder saves blank files
  packages/salesforcedx-vscode-soql/jest.config.js
  packages/salesforcedx-vscode-soql/package.json
  packages/salesforcedx-vscode-soql/src/queryDataView/queryDataFileService.ts
  packages/salesforcedx-vscode-soql/test/jest/queryDataView/queryDataFileService.test.ts
  packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
  scripts/setup-jest.ts
Labels: type:community-contrib

#4784 Pr/4761
  packages/salesforcedx-vscode-core/src/util/metadataDictionary.ts
  packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts
Labels: cla:signed

#4806 Pr/4787
  docs/_includes/header.html
Labels: cla:signed

#4763 fix: added notes to the publishing doc on what to do when a release d…
  contributing/publishing.md
Labels: area:doc
